runtime: php
env: flex

runtime_config: document_root: public

skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:580tzjpHfUxTLeDJ2UuuW4JTqWeFB9c0udTGWMH1u1Y=
  APP_NAME: "virta"

  LOG_LEVEL: debug
